# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version  of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-10-13

version: '2'

services:
 # microservice for odsupercomponent
    odsupercomponent:
        build: .
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --id=5 --verbose=1 --configuration=/opt/opendlv.data/configuration"

 # microservice for adaptation-ksamclient
    adaptation-ksamclient:
        build: .
        depends_on:
            - odsupercomponent
        working_dir: /opt/opendlv.data/
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - .:/opt/opendlv.data
        network_mode: host
        ipc: host
        command: "/opt/opendlv/bin/opendlv-logic-adaptation-ksamclient --id=3 --cid=${CID}"

 # microservice for adaptation-ksamserver
    adaptation-ksamserver:
        build: .
        depends_on:
            - odsupercomponent
        working_dir: /opt/opendlv.data/
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - .:/opt/opendlv.data
        network_mode: host
        ipc: host
        command: "/opt/opendlv/bin/opendlv-logic-adaptation-ksamserver --id=4 --cid=${CID}"
